//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.24 at 08:39:48 PM EET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.soapdeneme.com/xml/product", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.soapdeneme.xml.product;
